/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/models/SkeletonMage/SkeletonMage.glb 
*/

import React from 'react'
import {useGraph} from '@react-three/fiber'
import {useGLTF, useAnimations} from '@react-three/drei'
import {SkeletonUtils} from 'three-stdlib'

export function SkeletonMage(props) {
    const group = React.useRef()
    const {scene, animations} = useGLTF('./models/SkeletonMage/SkeletonMage.glb')
    const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
    const {nodes, materials} = useGraph(clone)
    const {actions} = useAnimations(animations, group)
    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Root_Scene">
                <group name="RootNode">
                    <group name="Rig" scale={100}>
                        <primitive object={nodes.root}/>
                    </group>
                    <skinnedMesh name="Skeleton_Mage_ArmLeft" geometry={nodes.Skeleton_Mage_ArmLeft.geometry}
                                 material={materials.skeleton} skeleton={nodes.Skeleton_Mage_ArmLeft.skeleton}
                                 scale={100}/>
                    <skinnedMesh name="Skeleton_Mage_ArmRight" geometry={nodes.Skeleton_Mage_ArmRight.geometry}
                                 material={materials.skeleton} skeleton={nodes.Skeleton_Mage_ArmRight.skeleton}
                                 scale={100}/>
                    <skinnedMesh name="Skeleton_Mage_Body" geometry={nodes.Skeleton_Mage_Body.geometry}
                                 material={materials.skeleton} skeleton={nodes.Skeleton_Mage_Body.skeleton}
                                 scale={100}/>
                    <skinnedMesh name="Skeleton_Mage_Eyes" geometry={nodes.Skeleton_Mage_Eyes.geometry}
                                 material={materials.Glow} skeleton={nodes.Skeleton_Mage_Eyes.skeleton}
                                 position={[0, 1.216, 0]} scale={100}/>
                    <skinnedMesh name="Skeleton_Mage_Jaw" geometry={nodes.Skeleton_Mage_Jaw.geometry}
                                 material={materials.skeleton} skeleton={nodes.Skeleton_Mage_Jaw.skeleton}
                                 position={[0, 1.312, -0.033]} scale={100}/>
                    <skinnedMesh name="Skeleton_Mage_LegLeft" geometry={nodes.Skeleton_Mage_LegLeft.geometry}
                                 material={materials.skeleton} skeleton={nodes.Skeleton_Mage_LegLeft.skeleton}
                                 scale={100}/>
                    <skinnedMesh name="Skeleton_Mage_LegRight" geometry={nodes.Skeleton_Mage_LegRight.geometry}
                                 material={materials.skeleton} skeleton={nodes.Skeleton_Mage_LegRight.skeleton}
                                 scale={100}/>
                    <skinnedMesh name="Skeleton_Mage_Skull" geometry={nodes.Skeleton_Mage_Skull.geometry}
                                 material={materials.skeleton} skeleton={nodes.Skeleton_Mage_Skull.skeleton}
                                 position={[0, 1.216, 0]} scale={100}/>
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('./models/SkeletonMage/SkeletonMage.glb')
