/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/models/monsters/Alien.glb 
*/

import React, {useEffect} from 'react'
import {useGraph} from '@react-three/fiber'
import {useGLTF, useAnimations} from '@react-three/drei'
import {SkeletonUtils} from 'three-stdlib'
import {useGameStore} from "../../store.js";
import {LoopOnce} from "three";

export function Alien({monsterId, ...props}) {
    const group = React.useRef()
    const {scene, animations} = useGLTF('./models/monsters/Alien.glb')
    const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
    const {nodes, materials} = useGraph(clone)
    const {actions} = useAnimations(animations, group)
    const monsterAnimation = useGameStore((state) => state.monsters[monsterId].monsterAnimation)

    if (actions['CharacterArmature|Death']) {
        actions['CharacterArmature|Death'].loop = LoopOnce
        actions['CharacterArmature|Death'].clampWhenFinished = true
    }

    useEffect(() => {
        actions[monsterAnimation].reset().fadeIn(0.2).play()
        return () => {
            actions[monsterAnimation].fadeOut(0.2).play()
        }
    }, [actions, monsterAnimation])
    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Root_Scene">
                <group name="RootNode">
                    <group name="CharacterArmature" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                        <primitive object={nodes.Root}/>
                    </group>
                    <group name="Alien" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                        <skinnedMesh name="Alien_1" geometry={nodes.Alien_1.geometry} material={materials.Alien_Main}
                                     skeleton={nodes.Alien_1.skeleton}/>
                        <skinnedMesh name="Alien_2" geometry={nodes.Alien_2.geometry}
                                     material={materials.Alien_Secondary} skeleton={nodes.Alien_2.skeleton}/>
                        <skinnedMesh name="Alien_3" geometry={nodes.Alien_3.geometry} material={materials.Eye_White}
                                     skeleton={nodes.Alien_3.skeleton}/>
                        <skinnedMesh name="Alien_4" geometry={nodes.Alien_4.geometry} material={materials.Eye_Black}
                                     skeleton={nodes.Alien_4.skeleton}/>
                        <skinnedMesh name="Alien_5" geometry={nodes.Alien_5.geometry} material={materials.Tongue}
                                     skeleton={nodes.Alien_5.skeleton}/>
                    </group>
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('./models/monsters/Alien.glb')
